# Generated by Django 4.1.3 on 2022-12-05 05:59

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登录时间')),
                ('login_ip', models.CharField(default='', max_length=10, verbose_name='登录IP')),
                ('equirement_type', models.CharField(default='', max_length=200, verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '登录信息',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='UserOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('expiration', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('type', models.CharField(choices=[('0', '查询'), ('1', '修改'), ('2', '导入')], max_length=1)),
            ],
            options={
                'verbose_name': '操作信息',
                'verbose_name_plural': '操作信息',
                'ordering': ['-expiration'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('user_addtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录添加日期')),
                ('user_number', models.CharField(default='', max_length=10, verbose_name='员工编号')),
                ('user_department', models.CharField(default='', max_length=50, verbose_name='所在部门')),
                ('user_role', models.CharField(default='', max_length=50, verbose_name='担任角色')),
                ('user_phone', models.CharField(default='', max_length=20, verbose_name='手机号码')),
                ('user_avator', models.ImageField(upload_to='static/imgs/', verbose_name='用户头像')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
